### PR TITLE
Update ReactHover.js

### PR DESCRIPTION
**Pull request by roczki93**
Added new CSS property in hover container. I added z-index property to show on front site content in hover. I had a problem with text in background. The background text was over the content of the balloon - this change fixed them.

### CODE REVIEW

**Comment by cht8687** [comment]
thanks for the change @roczki93

**Comment by cht8687** [comment]
Hi @roczki93 
I am just wondering, why don't you configure the zIndex css in your hover component? 
something like here: https://github.com/cht8687/react-hover/blob/master/src/example/Example.js#L62
in this way, zIndex is not tied with fix number, so people can change it according to fit their need.

**Comment by roczki93** [comment]
Hi cht8687,
I would like to show you my principle:
` <ReactHover.Hover type='hover' > <==HERE I NEED A CUSTOM Z-INDEX
                  <div className={componentstyles.hover} > <==THIS DIV
                    Albert Einstein
                    <blockquote className={componentstyles.quote}> Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. </blockquote>
                    <p className={componentstyles.people}>--Albert Einstein</p>
                  </div>
                </ReactHover.Hover>
              </ReactHover>`
I don't know how can I add in this place a custom styles. Please tell me, this is possible? When I changed styles in "THIS DIV" z-index doesn't work.
Thanks for your time, have a nice day!

**Comment by cht8687** [comment]
closing this PR. @roczki93 let me know if further work required we can reopen again.

**Pull request closed without merging**
